<?php

namespace App\Models;

class BaseSGD
{
    const BASES = [
        'Acervo educacional sobre água - ConhecerRH',
        'Acompanhamento das Cotas de Importação',
        'Aplicativo Água e Esgotos - Água e Esgotos',
        'Aplicativo Declara Água - Declara Água',
        'Arcos - Arcos',
        'Arquivos históricos digitais',
        'Banco Multidimensional de Estatísticas - BME',
        'Banco Nacional de Dados de Informação Meteorológica - INMET DB',
        'Base de Dados da Agricultura Brasileira - AGROBASE',
        'Base de Dados do SIEST (Sistema de Informações das Estatais) - SIEST',
        'Base SEPPI - SEPPI',
        'Biblioteca da ANEEL - SOPHIA',
        'Cadastro Ambiental Rural - CAR',
        'Cadastro de Agentes - CDA',
        'Cadastro de Entidades e Planos - CADPREVIC',
        'Cadastro de Imóveis Funcionais - CIF',
        'Cadastro de Inadimplentes - INADIMPLENTES',
        'Cadastro de Inspeções de Segurança de Barragens - Inspeção Barragem',
        'Cadastro de Levantamentos Aeroespaciais do Território Nacional - CLATEN',
        'Cadastro de Processos Jurídicos - SCPJ',
        'Cadastro de Servidores e Colaboradores da ANEEL - SISRH 2',
        'Cadastro Nacional de Dirigentes - CAND',
        'Cadastro Nacional de Informações Sociais - CNIS',
        'Cadastro Nacional de Usuários de Recursos Hídricos - CNARH40',
        'Cadastro Nacional de Usuários de Recursos Hídricos – Histórico - CNARH_HISTORICO',
        'Cadeia Societária - POLÍMERO',
        'Cálculo da Tarifa de Referência - CTR',
        'Cálculo da Taxa de Fiscalização - CALCULOTAXA',
        'Catraca',
        'Certificação de Entidades e Técnicos - CET',
        'CMCE',
        'CNIS - Segurado Especial - CNISSE',
        'Compensação Financeira pela Utilização de Recursos Hídricos - CMPFRH',
        'Concórdia ',
        'Controle da Dívida Ativa - SCDA',
        'Controle da Taxa de Fiscalização - TAXA',
        'Controle de Acesso - ACESSONET',
        'Controle de Acesso - Ccure',
        'Controle de Almoxarifado - SIADS',
        'Controle de Frota - SIADS',
        'Controle de Numeração - Numerar',
        'Controle de Patrimônio - SIADS',
        'Controle de Processos da SCG - CPSCG',
        'Controle de Processos da SMA - Processos',
        'Cordilheira - CAD',
        'Cotas de Exportação',
        'Dados da Cacauicultura no Estado do Pará - Dados da Cacauicultura no Estado do Para',
        'Dados de Pequenas Centrais Hidrelétricas/Eólicas - PCH/EOL',
        'Dados de Usinas Hidrelétricas - UHE',
        'Dados diversos referente à arrecadação de loterias',
        'Dados diversos referente às promoções comerciais',
        'Dados do Sistema de Acompanhamento de Manutenção - SAM',
        'Dados do Sistema Integrado de Pertubações - SIPER',
        'Data Warehouse do SIEST - SIEST DW',
        'Declaração de Aptidão ao PRONAF - DAP',
        'Demonstrações Atuariais da EFPC - Demonstrações Atuariais',
        'Determinações da Diretoria - SISCADE',
        'Dívida Ativa SIDA',
        'e-Consular',
        'E-docs - edocs',
        'Empresas usuárias de drawback suspensão e isenção',
        'Empresas.NET - ENET',
        'Estatística de Anistiados - Anistia',
        'Estatística de Atividades em Missão de Paz no Líbano - MPLibano',
        'Estatística de Atividades em Missões de Paz no Haiti - MPHaiti',
        'Estatística de Contratos da administração central do Ministério da Defesa - Contratos ACMD',
        'Estatística de Execução Orçamentária das unidades do Ministério da Defesa - Execução_Orçamentária_MD',
        'Estatística de Série Histórica Global da Execução Orçamentária do MD - Execução Orçamentária',
        'Estatísticas do Projeto Soldado Cidadão - Soldado Cidadão',
        'Estatístico de População e Benefício - EPB',
        'Ferramenta de Rasterização de Séries Temporais - FRST - FRST',
        'Formulário de Avaliação de Desempenho - FAD',
        'Formulário de Segurança de Barragens - FSB',
        'Formulários Dinâmicos de Gestão de Políticas de Desenvolvimento Tecnológico - FORMS.MCTI',
        'Fundo de Defesa da Economia Cafeeira - FUNCAFÉ',
        'Geoespacial da Área de Floresta - GEO',
        'Gestão de Contas - GDC',
        'Gestão de contratos convênios e licitações',
        'Gestão de Informações de Campos Eletromagnéticos - GCEM',
        'Gestão de Outorgas de Geração - OUTORGAS',
        'Gestão de Usuários - GU',
        'Gestão Eletrônica de Documentos - SICNET',
        'Gestão Integrada de Pessoas - GIP',
        'HelpDesk SASG e TI',
        'Iconografia',
        'Indicadores - BI',
        'Indicadores de Qualidade - INDQUAL',
        'Índice Aneel de Situação das Outorgas de Geração - IASO/G',
        'Índice Aneel de Situação das Outorgas de Transmissão - IASO/T',
        'Índice de Concorrência dos Municípios - ICM',
        'Inscrições em Leilões - LEILÃO',
        'Instrução do Processo Decisório - SIPD',
        'Intranet',
        'Inventário de Ativos de TI - OCS Inventory',
        'Inventário de Ativos de TI Base de Conhecimento TI HelpDesk TI - GLPI',
        'Inventário Florestal Nacional - IFN',
        'Lista consolidada de resultados de apuração nacional',
        'Lista Oficial de Embarcações Pesqueiras Habilitadas para Exportação à UE',
        'Mais gestão',
        'Mapa Interativo',
        'Monitoramento de Rede - Zabbix',
        'Movimento nos últimos 12 meses - Drawback Isenção',
        'Movimento nos últimos 12 meses - Drawback Suspensão',
        'Novos Empreendimentos de Geração - SKATE',
        'Obter Crédito Terra Brasil',
        'Painel de Gestão da Capacitação',
        'Participação Acionária em Empreendimentos - PARACEMP',
        'Participações sociais das agências reguladoras',
        'Plataforma de Pesquisas da Legislação da Defesa - MDLEGIS',
        'Ponto Eletrônico - PONTONET',
        'Portal A3P - Portal A3P',
        'Portal Colaborativo - PCSPU',
        'Portal Consular',
        'Portal de Informações Agropecuárias - Portal da CONAB',
        'Portal de Metadados Geoespaciais da ANA - Metadados',
        'Portal de Serviços da SPU - PORTAL SPU',
        'Portal de venda de imóveis da União - VENDASGOV',
        'Portal Itamaraty',
        'Portal sobre o Programa Calha Norte - Vertente Civil - PCN - Civil',
        'Portal sobre o Projeto Rondon - Projeto Rondon',
        'Processos Tramitados',
        'Programa Nacional de Desenvolvimento da Pesca Amadora - PNDPA',
        'Programa Nacional de Melhoria da Qualidade do Leite - PNQL',
        'PROTON - Módulo de Cultivare Protegidos - PROTON',
        'Recebimento de Arquivos Eletrônicos - DUTO/DUTONET',
        'REDD+ Brasil - REDD+ Brasil',
        'Relatório de dados consolidados de drawback suspensão e isenção',
        'Relatórios de Monitoramento sobre os Contratos de Gestão firmados pelo ME',
        'Repositório da Memória das Olimpíadas',
        'Repositório Rui Barbosa de Informações Culturais   - Rubi',
        'Rol de documentos Classificados e Desclassificados - Rol',
        'SCI - sci',
        'SEPROD',
        'Service Desk da ANEEL - SYSAID',
        'Serviço Militar Obrigatório - SMO',
        'Sistema Brasileiro de Rastreabilidade da Cadeia Produtiva de Bovinos e Bubalinos - SISBOV',
        'Sistema Brasileiro de Vigilância e Emergência Veterinária - E-SISBRAVET',
        'Sistema Cadeia de Custódia - SCC',
        'Sistema Channel - Channel',
        'Sistema de Acompanhamento da Produção Canavieira - SAPCANA',
        'Sistema de Acompanhamento de Mercado Padronizado - SAMP',
        'Sistema de Acompanhamento de Obras - SIURB',
        'Sistema de Acompanhamento de Processos - SAP',
        'Sistema de Acompanhamento de Reservatórios - SAR',
        'Sistema de Acompanhamento e Monitoramento Hidrológico do Setor Elétrico - SANSE',
        'Sistema de Acompanhamento e Relacionamento Institucional - SARI',
        'Sistema de Acompanhamento Parlamentar - RADAR',
        'Sistema de Administração de Créditos e Inadimplentes - PLUTUS',
        'Sistema de Administração de Receitas Patrimoniais - SARP',
        'Sistema de Administração dos postos - ADMP',
        'Sistema de Análise de Dados Hidrometeorológicos - SIADH',
        'Sistema de Apoio a Gestão de Contratos de Prestação de Serviços - SAGE',
        'Sistema de Apoio às Fiscalizações da ANEEL - SAFIRA',
        'Sistema de Arrecadação - Arrecadação',
        'Sistema de Atos Normativos - Atos Normativos',
        'Sistema de Autenticação, Autorização e Auditoria - S3A',
        'Sistema de Avaliação de Desempenho - FAD/SISAVE',
        'Sistema de Avaliação de Desempenho de Servidores - RH - Avaliação',
        'Sistema de Biblioteca Virtual - SOPHIA',
        'Sistema de Cadastramento de Produtos e Empresas de Defesa - SISCAPED',
        'Sistema de Câmbio - SICAM',
        'Sistema de Capacitação de Servidores - RH - Capacitação',
        'Sistema de Cobrança - DIGICOB II',
        'Sistema de Colegiados - Colegiados',
        'Sistema de Contabilidade - SISCONT',
        'Sistema de Controle de Almoxarifado e Patrimônio - ASI-WEB',
        'Sistema de Controle de Reclamações - SCR',
        'Sistema de Controle de Recursos Humanos - SRH',
        'Sistema de Controle de Reuniões da Diretoria - SICOR',
        'Sistema de Controle de Subvenções e Programas Sociais - SCS',
        'Sistema de Credenciamento da ANEEL - SCA',
        'Sistema de Curso de Extensão em Defesa Nacional - CEDN',
        'Sistema de Disponibilização de Informações Hidrológicas - HIDROWEB',
        'Sistema de Gerenciamento das Ações do Biodiesel - SABIDO',
        'Sistema de Gerenciamento de Estudos Epidemiológicos - SIGEP',
        'Sistema de Gerenciamento de Outorgas em Tanque Rede - Tanque Rede',
        'Sistema de Gerenciamento dos Imóveis de Uso Especial da União - SPIUNet',
        'Sistema de Gestão da Lei de Informática - NovoSigplani',
        'Sistema de Gestão da Ouvidoria Setorial - SGO',
        'Sistema de Gestão da Transmissão - SIGET',
        'Sistema de Gestão das Fiscalizações - SIGEFIS',
        'Sistema de gestão de atividades da Semana Nacional de Ciência e Tecnologia - SNCT',
        'Sistema de Gestão de Auditoria Interna - MSIGAIN',
        'Sistema de Gestão de Capacitação para o SINGREH - SABERH',
        'Sistema de Gestão de Concessão Florestal - GCF',
        'Sistema de Gestão de Contratos - SGC',
        'Sistema de Gestão de Contratos e Convênios - SICON',
        'Sistema de Gestão de Créditos - SIGEC',
        'Sistema de Gestão de Dados Hidrológico enviados por SMS - GDH-SMS',
        'Sistema de Gestão de Equipamentos Telemétricos e Dados   - Gestor PCD',
        'Sistema de Gestão de Investimento em Pesquisa e Desenvolvimento - SIPED',
        'Sistema de Gestão de Laboratórios - SISLAB',
        'Sistema de Gestão de Planejamento Estratégico da Aneel - SIGEA',
        'Sistema de Gestão do Programa de P&D - SGPED',
        'Sistema de Gestão Fundiária - SIGEF',
        'Sistema de Gestão Integrada - SGI',
        'Sistema de Gestão Integrada dos Imóveis Públicos Federais - SPUNET',
        'Sistema de Importação dos Arquivos do SIAFI - SIAS',
        'Sistema de Indicações Geográficas e Marcas - SIGMA',
        'Sistema de Informação de Requisitos e Certificados da Área Animal - SISREC',
        'Sistema de Informações de Geração da ANEEL - SIGA',
        'Sistema de Informações Documentais - Próton',
        'Sistema de Informações em Biossegurança - SIB',
        'Sistema de Informações Gerenciais de Produtos de Origem Animal - SIGPOA',
        'Sistema de Informações Gerenciais do Crédito Fundiário - SIGCF',
        'Sistema de Informações Gerenciais do Serviço de Inspeção Federal - SIGSIF',
        'Sistema de Informações Hidrológicas - HIDRO',
        'Sistema de Inquéritos (Sistema Sancionador Integrado) - INQ (SSI)',
        'Sistema de Julgamento de Recursos da Comissão Especial de Recursos - SISPROCER',
        'Sistema de Licitações de Contratos de Execução Física - SLCEF',
        'Sistema de Licitações e Contratos - SLC',
        'Sistema de Monitoramento da Agenda Ambiental na Administração Pública - RESSOA',
        'Sistema de Monitoramento de Atos Normativos - SISMAN',
        'Sistema de Monitoramento Hidrológico em tempo Real - HIDRO - Telemetria',
        'Sistema de Monitoramento Via Satélite - HIDROSAT',
        'Sistema de Planejamento do Desporto Militar - SISATLETA',
        'Sistema de Planejamento, Orçamento e Gestão da ANA - SISPLANA',
        'Sistema de Previsão de Eventos Críticos na bacia do Rio Paraíba do Sul - SISPREC',
        'Sistema de Próprios Nacionais Residenciais - SISPNR',
        'Sistema de Protocolo Digital - SPD',
        'Sistema de Recursos Humanos - RH',
        'Sistema de Registro de Atividade Pesqueira da Tainha - SISTAINHA',
        'Sistema de Registro de Geração Distribuída - SISGD',
        'Sistema de Registro Geral da Pesca e Aquicultura - SISRGP',
        'Sistema de Requerimento Eletrônico de Imóveis - SISREI',
        'Sistema de Requisição Veicular - SISRV',
        'Sistema de Supervisão do Mercado de Capitais Brasileiro - SAM',
        'Sistema de Suporte a Decisão da SPU - SSD/DW',
        'Sistema de Suporte a Decisão para Outorga - SSDO',
        'Sistema de Tarifa Locacional - STL',
        'Sistema de Zoneamento do Risco Climático - SISZARC',
        'Sistema do Atlas de Abastecimento Urbano de Água - Atlas Brasil',
        'Sistema do Congresso Acadêmico sobre Defesa Nacional - CADN',
        'Sistema do Programa Produtor de Água - Produtor de Água',
        'Sistema Eletrônico de Informações - Pensei Digital',
        'Sistema Eletrônico de Informações - SEI',
        'Sistema Federal de Regulação de Uso - REGLA',
        'Sistema IBGE de Recuperação Automática - SIDRA',
        'Sistema Informatizado de Assistência Técnica e Extensão Rural - SIATER',
        'Sistema Informatizado Mais Alimentos',
        'Sistema Integrado de Gestão e Execução Financeira - SIGEF',
        'Sistema Integrado de Administração Patrimonial - SIAPA',
        'Sistema Integrado de Gestão da ANEEL - SIGANEEL',
        'Sistema Integrado de Gestão Documental - SIGED',
        'Sistema Integrado de Gestão e Controle do Espectro - MOSAICO',
        'Sistema Integrado de Planejamento e Orçamento / Orçamento de Investimento das Estatais (SIOP/OI) - SIOP OI',
        'Sistema Nacional de Certificação de Unidades Armazenadoras - SNCUA',
        'Sistema Nacional de Informação sobre Segurança de Barragem - SNISB',
        'Sistema Nacional de Informações de Registro Civil - SIRC',
        'Sistema Nacional de Informações sobre Recursos Hídricos - SNIRH',
        'Sistema Nacional de Registro de Emissões - SIRENE',
        'Sistema para Apresentação de Estatísticas da Rede Hidrometeorológica - SiEst',
        'Sistema para Avaliação do Desempenho da Operação da Rede Hidrometeorológica - SiADORHA',
        'Sistema Telegráfico - SICOM',
        'Sistema Visualizador das Fichas de Campo das Estações Hidrometeorologicas - Fichas de Campo das Estações',
        'Site SPU - Imóveis Dominiais - Balcão Virtual',
        'Sítio da ANEEL - LIFERAY',
        'Sophia',
        'Thesaurus Agrícola Nacional - THESAGRO',
        'Tramitação de processos administrativos físicos',
        'Uso de Bem Público - UBP',
        'Vídeo monitoramento',
    ];
}
